### ISSUE TITLE
Fine_dehalo mask is broken at fp32 bitdepth

### ISSUE THREAD

**Issue by Vodes** [Jaded-Encoding-Thaumaturgy/vs-dehalo#48]
Don't have a sample and/or comp for it but it's been pointed out by multiple people on the discord before.

**Comment by Setsugennoao** [comment]
After investigating, the only difference is Robinson3 being way more sensitive in float32
As it's supposed to be different at different bitdepths, if you want a better output, configure fine_dehalo with another edgemask
