### ISSUE TITLE
pre_ss shifts image

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/vs-dehalo#49]
On latest, using `pre_ss` with any of the dehaloing functions causes the image to shift. 

[comp](https://slow.pics/c/ye2px6zQ)

```py
dehalo_sigma(clip, pre_ss=1)
dehalo_sigma(clip, pre_ss=2)
```

**Comment by Setsugennoao** [comment]
Have you updated sneedif?

**Comment by LightArrowsEXE** [comment]
Just updated and it still happens.

**Comment by LightArrowsEXE** [comment]
Fixed in https://github.com/Jaded-Encoding-Thaumaturgy/vs-kernels/pull/37
